routes/web.php
<?php

use App\Http\Controllers\MineController;
use App\Http\Controllers\ScoreController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SnakeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdministrarController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('snake',SnakeController::class)->middleware('auth');
Route::resource('score',ScoreController::class)->middleware('auth');
Route::resource('mine',MineController::class)->middleware('auth');
Route::resource('user',UserController::class)->middleware('auth');
Route::resource('administrar',AdministrarController::class)->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Route;
class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function snake()
    {
        $nombreRuta = Route::currentRouteName();
        if ($nombreRuta == 'score.index'){
            return $this->hasMany(Snake::class)->orderBy('score','DESC')->take(1);
        }
        return $this->hasMany(Snake::class)->orderBy('score','DESC')->take(5);
    }
    public function mine()
    {
        $nombreRuta = Route::currentRouteName();
        if ($nombreRuta == 'score.index'){
            return $this->hasMany(Mine::class)->orderBy('minutos')->orderBy('segundos')->orderBy('centesimas')->take(1);
        }
        return $this->hasMany(Mine::class)->orderBy('minutos')->orderBy('segundos')->orderBy('centesimas')->take(5);
    }
    public function role()
        {
            return $this->belongsTo(Role::class);
        } 
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        if(Auth::user()->role_id == 2){
            return view('user.admin',['users' => $users]);
        }
        else{
            return view('user.index',['users' => $users]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('layouts.app',['user'=>$user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = User::find($id);
        if(Auth::user()->role_id == 2){
            return view('user.adminedit',['usuario' => $usuario]);
        }
        else {
            return view('user.edit',['usuario'=>$usuario]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $usuario = User::find($id);
        $usuario->name = $request->input('name');
        $usuario->email = $request->input('email');
        $usuario->save();
        return redirect('user')->with('status','Usuario modificado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usuario = User::find($id);
        if(Auth::user()->role_id == 2){
           $usuario->snake()->delete();
           $usuario->mine()->delete();
           $usuario->delete();
           return redirect('user')->with('status','Usuario eliminado');
        }
        $usuario->delete();
        return redirect('register')->with('status','Usuario eliminado');
    }
}

resources/views/user/admin.blade.php
@extends('layouts.app')

@section('content')
@if (session('status'))
<div class="alert alert-success">
    {{ session('status') }}
</div>
@endif
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Email</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        <tr>
            @foreach($users as $user)
        <tr>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>
                <a href="{{route('user.edit',$user->id)}}" class="btn btn-warning ">Editar usuario</a>
            </td>
            <td>
            <form action="{{route('user.destroy',$user->id)}}" method="POST">
                @csrf
                @method('DELETE')
                <input type="submit" class="btn btn-danger" value="Eliminar cuenta">
            </form>
        </td>
        </tr>
        @endforeach
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
@endsection

resources/views/user/adminedit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h4>Editar usuario</h4>
    <div class="row">
        <div class="col-xl-12">
            <form action="{{route('user.update',$usuario->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Nombre</label>
                    <input type="text" class="form-control" name="name" required maxlength="30" value="{{$usuario->name}}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" required maxlength="50" value="{{$usuario->email}}">
                </div>
                <input class="btn btn-primary block" type="submit" value="Guardar usuario">
        </div>
    </div>
</div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h4>Editar usuario</h4>
    <div class="row">
        <div class="col-xl-12">
            <form action="{{route('user.update',Auth::user()->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Nombre</label>
                    <input type="text" class="form-control" name="name" required maxlength="30" value="{{Auth::user()->name}}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" required maxlength="50" value="{{Auth::user()->email}}">
                </div>
                <input class="btn btn-primary block" type="submit" value="Guardar usuario">
            </form>

        </div>
    </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
@if (session('status'))
<div class="alert alert-success">
    {{ session('status') }}
</div>
@endif
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Email</th>
            <th scope="col">Editar</th>
            <th scope="col">Eliminar</th>
        </tr>
        <tr>
            <td>{{Auth::user()->name}}</td>
            <td>{{Auth::user()->email}}</td>
            <td>
                <a href="{{route('user.edit',Auth::user()->id)}}" class="btn btn-warning ">Editar usuario</a>
            </td>
            <td>
                <form action="{{route('user.destroy',Auth::user()->id)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <input type="submit" class="btn btn-danger" value="Eliminar cuenta">
                </form>
            </td>
        </tr>
    </thead>
</table>
<table class="table text-center">
    <thead>
        <tr class="table-success">
            <th scope="col">Puntuaciones Snake</th>
        </tr>
        @foreach ($users as $user)
        @if($user->id == Auth::user()->id )
        @foreach ($user->snake as $puntosSnake)
        <tr>
            <td class="table-light"><b>{{$puntosSnake->score}}</b></td>
        </tr>
        @endforeach
        @endif
        @endforeach
    </thead>
</table>
<table class="table text-center">
    <thead>
        <tr class="table-success">
            <th scope="col">Puntuaciones Buscaminas</th>
        </tr>
        @foreach ($users as $user)
        @if($user->id == Auth::user()->id )
        @foreach ($user->mine as $puntos)
        <tr>
            <td class="table-light"><b>{{$puntos->minutos}}:{{$puntos->segundos}}:{{$puntos->centesimas}}</b></td>
        </tr>
        @endforeach
        @endif
        @endforeach
    </thead>
</table>
@endsection